#!/usr/bin/env node
'use strict';

const assert = require('node:assert/strict');
const test = require('node:test');

const {
  parseYarnLockBlocks,
  serializeYarnLockBlocks,
  parseKeySpecs,
  nameToPattern,
  blockMatchesPackage,
  blockMatchesAnyPackage,
  deleteYarnLockBlocksByPackageNames,
} = require('./yarnLockBlocks.js');

const SIMPLE_LOCK = `# This file is generated by running "yarn install" inside your project.
__metadata:
  version: 8
  cacheKey: 10

"eslint@npm:^8.0.0":
  version: 8.57.1
  resolution: "eslint@npm:8.57.1"
  languageName: node
  linkType: hard

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  languageName: node
  linkType: hard
`;

const COMBINED_KEY_LOCK = `__metadata:
  version: 8

"@internal/app@workspace:^, @internal/app@workspace:packages/app":
  version: 0.0.0-use.local
  resolution: "@internal/app@workspace:packages/app"
  languageName: unknown
  linkType: soft

"@internal/backend@workspace:packages/backend":
  version: 0.0.0-use.local
  resolution: "@internal/backend@workspace:packages/backend"
  languageName: unknown
  linkType: soft
`;

const PATCH_LOCK = `__metadata:
  version: 8

"@backstage/core-plugin-api@patch:@backstage/core-plugin-api@npm%3A1.9.3#./.yarn/patches/x.patch::version=1.9.3&hash=abcd":
  version: 1.9.3
  resolution: "@backstage/core-plugin-api@patch:@backstage/core-plugin-api@npm%3A1.9.3#./.yarn/patches/x.patch::version=1.9.3&hash=abcd::locator=x"
  languageName: node
  linkType: hard

"react@npm:^18.0.0":
  version: 18.3.1
  resolution: "react@npm:18.3.1"
  languageName: node
  linkType: hard
`;

test('parseYarnLockBlocks + serializeYarnLockBlocks round-trips unmodified content exactly', () => {
  for (const fixture of [SIMPLE_LOCK, COMBINED_KEY_LOCK, PATCH_LOCK]) {
    const parsed = parseYarnLockBlocks(fixture);
    assert.equal(serializeYarnLockBlocks(parsed), fixture);
  }
});

test('parseYarnLockBlocks separates preamble from entries', () => {
  const parsed = parseYarnLockBlocks(SIMPLE_LOCK);
  assert.equal(parsed.blocks.length, 2);
  assert.match(parsed.preamble.join('\n'), /generated by running "yarn install"/);
  assert.match(parsed.preamble.join('\n'), /__metadata:/);
  assert.equal(parsed.blocks[0].key, '"eslint@npm:^8.0.0":');
  assert.equal(parsed.blocks[1].key, '"lodash@npm:^4.17.21":');
});

test('parseKeySpecs splits combined keys and strips quotes/colon', () => {
  const specs = parseKeySpecs('"@internal/app@workspace:^, @internal/app@workspace:packages/app":');
  assert.deepEqual(specs, ['@internal/app@workspace:^', '@internal/app@workspace:packages/app']);
});

test('parseKeySpecs handles a single-spec key', () => {
  assert.deepEqual(parseKeySpecs('"eslint@npm:^8.0.0":'), ['eslint@npm:^8.0.0']);
});

test('nameToPattern anchors on exact package name, escaping regex metacharacters', () => {
  const pattern = nameToPattern('@backstage/core-plugin-api');
  assert.equal(pattern.test('@backstage/core-plugin-api@npm:1.9.3'), true);
  assert.equal(pattern.test('@backstage/core-plugin-api-extra@npm:1.9.3'), false);
});

test('nameToPattern treats @internal/ANY as a wildcard for any @internal/* spec', () => {
  const pattern = nameToPattern('@internal/ANY');
  assert.equal(pattern.test('@internal/app@workspace:^'), true);
  assert.equal(pattern.test('@internal/backend@workspace:packages/backend'), true);
  assert.equal(pattern.test('lodash@npm:^4.17.21'), false);
});

test('blockMatchesPackage checks every spec in a combined key, not just the first', () => {
  const parsed = parseYarnLockBlocks(COMBINED_KEY_LOCK);
  const [appBlock] = parsed.blocks;
  // Matches via the second spec, not the first — the original only
  // anchored against the whole key line and would have missed this.
  assert.equal(blockMatchesPackage(appBlock, '@internal/app'), true);
});

test('blockMatchesAnyPackage matches against a list', () => {
  const parsed = parseYarnLockBlocks(SIMPLE_LOCK);
  assert.equal(blockMatchesAnyPackage(parsed.blocks[1], ['react', 'lodash']), true);
  assert.equal(blockMatchesAnyPackage(parsed.blocks[0], ['react', 'lodash']), false);
});

test('deleteYarnLockBlocksByPackageNames removes matching blocks and preserves the rest', () => {
  const { content, removed } = deleteYarnLockBlocksByPackageNames(SIMPLE_LOCK, ['lodash']);
  assert.deepEqual(removed, ['"lodash@npm:^4.17.21":']);
  assert.doesNotMatch(content, /lodash/);
  assert.match(content, /eslint/);
  // Result should itself still be a valid, round-trippable lock.
  const reparsed = parseYarnLockBlocks(content);
  assert.equal(reparsed.blocks.length, 1);
});

test('deleteYarnLockBlocksByPackageNames is idempotent (no-op on a second pass)', () => {
  const first = deleteYarnLockBlocksByPackageNames(SIMPLE_LOCK, ['lodash']);
  const second = deleteYarnLockBlocksByPackageNames(first.content, ['lodash']);
  assert.equal(second.content, first.content);
  assert.deepEqual(second.removed, []);
});

test('deleteYarnLockBlocksByPackageNames supports the @internal/ANY wildcard for bulk cleanup', () => {
  const { content, removed } = deleteYarnLockBlocksByPackageNames(COMBINED_KEY_LOCK, ['@internal/ANY']);
  assert.equal(removed.length, 2);
  assert.doesNotMatch(content, /@internal\//);
});

test('deleteYarnLockBlocksByPackageNames leaves non-matching combined-key blocks untouched', () => {
  const { content } = deleteYarnLockBlocksByPackageNames(COMBINED_KEY_LOCK, ['@internal/backend']);
  assert.match(content, /@internal\/app@workspace/);
  assert.doesNotMatch(content, /@internal\/backend/);
});
